apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: cinema-clickhouse
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: cinema_user
      defaultDatabase: cinema
      tlsSkipVerify: true
    secureJsonData:
      password: cinema_pass
    editable: true
